#ifndef __CONFIG_H__
#define __CONFIG_H__

#include <stdbool.h>

#define sizeofarray(x)  sizeof(x)/sizeof(x[0])

typedef struct config_t {
    /* Database Variables configured by user */
    char db_host[128];
    char db_database[128];
    char db_user[128];
    char db_passwd[128];

    /* Database Connection String generated by program */
    char db_conn_string[1024];

    /* Spacetrack Credentials configured by user */
    char spacetrack_user[128];
    char spacetrack_passwd[128];

    /* Earth Station Position configured by user */
    double latitude;
    double longitude;
    double altitude;
    /* Earth Station Tracking Variables configured by user */
    double azimuth_endstop;
    double azimuth_rate;
    double elevation_rate;

    /* Scheduler Variables configured by user */
    double minimum_interval;
    double minimum_period;
} config_t;

config_t config;

bool config_load(config_t *config, char *filename);

#endif /* __CONFIG_H__ */
